 

exports.skills =[
   "Plant Identification" ,
   "FS-CD" ,
   "Hiring" ,
   "DG Sets" ,
   "LCL" ,
   "Global Marketing" ,
   "FCPA" ,
   "HTML" ,
   "Mobile Marketing" ,
   "OSGi" ,
   "CFML" ,
   "CBRN" ,
   "JDF" ,
   "Permanent Placement" ,
   "WS" ,
   "Digital Electronics" ,
   "Theology" ,
   "xSeries" ,
   "IPv" ,
   "Vector Illustration" ,
   "Kaizen Leadership" ,
   "Zynx" ,
   "NRF" ,
   "Nightlife" ,
   "JDK" ,
   "Two-factor Authentication" ,
   "Tax" ,
   "OOS" ,
   "NWDS" ,
   "Typewriter"];